---
# 0 6 1 * *

- name: Daily Hypervisor
  hosts: hypervisor
  become: false
  gather_facts: false
  roles:
    - role: run_smart_test
      vars:
        test_type: "{{ smart_test_types.short }}"
    - role: check_smart_status
      vars:
        always_notify: true
