---
- name: Update packages, auto clean and auto remove
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true
    autoclean: true
    update_cache: true

- name: Check if restart is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_flag_results

- name: Get list of VMs pending restart
  vars:
    value: "{{ hostvars[item] }}"
  ansible.builtin.set_fact:
    vms_pending_restart: "{{ vms_pending_restart | default([]) + [item]}}"
  loop: "{{ hostvars.keys() }}"
  when:
    - value.reboot_flag_results.failed is defined
    - not value.reboot_flag_results.failed
    - value.reboot_flag_results.stat.exists
  delegate_to: localhost
  run_once: true

- name: Notify if restart is needed
  community.general.discord:
    webhook_id: "{{ webhook_id }}"
    webhook_token: "{{ webhook_token }}"
    username: "Ansible: Pending Reboot Alert"
    avatar_url: https://i.imgur.com/Z4tUwsx.png # Ansible Logo (White)
    embeds:
      - title: "VMs Need Restarting!!"
        color: "{{ discord_colors.minor }}"
        image:
          url: "https://i.imgur.com/fI2hS6r.png" # Restart Icon (white)
        fields:
          - name: "The following VMs require restarting:"
            value: "{{ vms_pending_restart | map('upper') | map('regex_replace', '^(.*)$', '- \\1') | join('\n') }}"
        footer:
          text: "Automatic Run"
  delegate_to: localhost
  run_once: true
  when:
    - vms_pending_restart is defined

