---
power_loss_scripts_path: /etc/shutdown-on-power-loss

power_loss_script_flags: flags.sh
power_loss_script_shutdown: shutdown-on-power-loss.sh
power_loss_script_set: set-flags.sh
power_loss_script_reset: reset-flags.sh
power_loss_script_view: view-flags.sh

power_loss_script_flags_path: "{{ power_loss_scripts_path }}/{{ power_loss_script_flags }}"
power_loss_flag_path: "{{ power_loss_scripts_path }}/was_used"
power_loss_script_cron_log_path: "{{ power_loss_scripts_path }}/cronjob.log"
power_loss_scripts:
  - "{{ power_loss_script_flags }}"
  - "{{ power_loss_script_set }}"
  - "{{ power_loss_script_reset }}"
  - "{{ power_loss_script_shutdown }}"
  - "{{ power_loss_script_view }}"

# cronjob script
router_ip: 192.168.1.1
ping_attempts: 3

# cronjob
power_loss_cronjob:
  minute: "*"
  hour: "*"
  day: "*"
  month: "*"
  weekday: "*"

# logrotate
logrotate_conf_path: /etc/logrotate.d/shutdown_on_power_loss
