---
- name: Gather User facts
  ansible.builtin.setup:
    gather_subset:
      - 'user_id'
      - 'user_gid'

- name: Run container
  containers.podman.podman_container:
    name: "{{ jellyfin_container_name }}"
    image: "{{ docker_private_registry }}/jellyfin/jellyfin:latest"
    state: created
    user: "{{ jellyfin_user }}:{{ jellyfin_group }}"
    publish:
      - 8096:8096/tcp
    userns: keep-id
    label:
      io.containers.autoupdate: registry
    volume:
      - jellyfin-cache:/cache:Z
      - jellyfin-config:/config:Z
      - "{{ jellyfin_smb_mnt_wrapper_path }}:/media/truenas,ro=true,relabel=private"
    generate_systemd:
      path: ~/.config/systemd/user/
      restart_policy: always
      stop_timeout: 120
      names: true
      container_prefix: "{{ systemctl_container_prefix }}"
      new: true
  register: jellyfin_container_create_result

- name: Reload systemctl daemon and start and enable container
  ansible.builtin.systemd_service:
    name: "{{ systemctl_container_prefix }}-{{ jellyfin_container_name }}"
    state: "{{ 'restarted' if jellyfin_container_create_result.changed  else 'started' }}"
    enabled: true
    scope: user
    daemon_reload: true

- name: Make sure podman-auto-update.timer is running and enabled
  become: true
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    state: started
    enabled: true
